### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by 0-LL-0** [karta0807913/caffe-yolo-9000#3]
Q1: Some tips occured to me when using 'make all -j8', are you annotated with the above code or the following code???
src/caffe/layers/yolo_v2_loss_layer.cpp:113:1: warning: "/*" within comment [-Wcomment]
 /* **/ 

yolo_v2_loss_layer.cpp:113
`/**/
        diff[index + 2 * SHIFT] = scale * (pred_box.w - truth_box.w) * pred_box.w;
        diff[index + 3 * SHIFT] = scale * (pred_box.h - truth_box.h) * pred_box.h;
/** /
        diff[index + 2 * SHIFT] = scale * (log(pred_box.w / biases[2 * n + 0])
                     - log(truth_box.w / biases[2 * n + 0]));
        diff[index + 3 * SHIFT] = scale * (log(pred_box.h / biases[2 * n + 1])
                     - log(truth_box.h / biases[2 * n + 1])); 
/* **/`
Q2：How to detec images through the voc_model_iter_30000.caffemodel you provide?

**Comment by karta0807913** [comment]
Q1: the following code, because log will make the gradient to Inf

Q2: use this at project
https://github.com/karta0807913/LabelingTools
Change mainwindow.cpp model, prototxt, mean to voc_model

**Comment by 0-LL-0** [comment]
Thank you very much for your reply and thank you for your sharing！
