### ISSUE TITLE
为啥编译错误

### ISSUE THREAD

**Issue by kanshichao** [karta0807913/caffe-yolo-9000#5]
.build_release/tools/convert_box_data.o：在函数‘main’中：
convert_box_data.cpp:(.text.startup+0x858)：对‘caffe::ReadBoxDataToDatum(std::string const&, std::string const&, std::map<std::string, int, std::less<std::string>, std::allocator<std::pair<std::string const, int> > > const&, int, int, bool, std::string const&, caffe::Datum*)’未定义的引用
collect2: 错误： ld 返回 1
make: *** [.build_release/tools/convert_box_data.bin] 错误 1

**Comment by karta0807913** [comment]
我這邊使用cmake編譯正常唷
你要不要試試看cmake
mkdir build: cd build;cmake ..;make;

**Comment by Ghustwb** [comment]
确实是的，如果用Makefile.config 的话就会出现编译错误。用cmake就可以了。

**Comment by kanshichao** [comment]
多谢，已经解决！
